// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

import type { KVNamespace, D1Database } from '@cloudflare/workers-types'

interface Env {
  URL_MAPPINGS: KVNamespace
  URL_ANALYTICS: KVNamespace
  API_KEYS: KVNamespace
  OG_METADATA_CACHE: KVNamespace
  DB: D1Database
}
