// Generated by Wrangler on Wed Aug 28 2024 14:30:49 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
	NUXT_DB_TYPE: "cf";
	REDIRECT_URL: "https://cf-examples-nuxt.pages.dev/";
	ALLOWED_CORS_ORIGINS: "*";
	DB: D1Database;
}
